### ISSUE TITLE
status ?

### ISSUE THREAD

**Issue by vrabaud** [nalt/webcontroller#1]
Hey, that is very cool, I was wondering why you never advertised it and what the future of it is. Thx !

**Comment by nalt** [comment]
Thanks for the reminder! I have been very busy with other projects - but we will publish some new features soon.

**Comment by krixkrix** [comment]
Just found this, sounds like a cool project, but I get a little worried seeing no updates in 3-4 years. How mature is this? Works with ROS kinetic? any videos or at least screenshots anywhere? Any serious plans on maintaining this? If not, do you know of alternatives out there?
